### ISSUE TITLE
Backtrace in PDL Live Viewer

### ISSUE THREAD

**Issue by esnible** [IBM/prompt-declaration-language#231]
**Describe the bug**
Backtrace in PDL Live Viewer:

```
index.cjs:1 Uncaught u: Pattern matching error: no pattern matches value {"with":""}
    at t.exhaustive (https://ibm.github.io/prompt-declaration-language/dist/bundle.js:217:11500)
    at show_loop_trace (https://ibm.github.io/prompt-declaration-language/dist/bundle.js:9795:10)
    at https://ibm.github.io/prompt-declaration-language/dist/bundle.js:9761:27
    at t.with (https://ibm.github.io/prompt-declaration-language/dist/bundle.js:217:11114)
    at show_block (https://ibm.github.io/prompt-declaration-language/dist/bundle.js:9759:14)
    at show_lastOf (https://ibm.github.io/prompt-declaration-language/dist/bundle.js:9571:32)
    at https://ibm.github.io/prompt-declaration-language/dist/bundle.js:9722:27
    at t.with (https://ibm.github.io/prompt-declaration-language/dist/bundle.js:217:11114)
    at show_block (https://ibm.github.io/prompt-declaration-language/dist/bundle.js:9720:14)
    at HTMLDivElement.<anonymous> (https://ibm.github.io/prompt-declaration-language/dist/bundle.js:9901:25)
```

**To Reproduce**
Open https://ibm.github.io/prompt-declaration-language/viewer/ and upload this JSON:
[trace.json](https://github.com/user-attachments/files/18201751/trace.json)

**Expected behavior**
Colored, clickable, data

**Desktop (please complete the following information):**
 - OS: MacBook
 - Browser: Version 131.0.6778.109 (Official Build) (arm64)

**Additional context**
Trace produced using `pdl --trace=trace.json --log log.txt agrabot8.pdl`

**Comment by esnible** [comment]
I see the same thing with the trace produced by the Chatbot example `pdl --trace /tmp/chatbot.trace ./chatbot.pdl`.

**Comment by vazirim** [comment]
@starpit Could you please check if your UI has these issue as well?

**Comment by vazirim** [comment]
This is fixed in the new UI.
